In [1]:
import numpy as np
n=int(input('enter the number of pages: '))
d=float(input('enter the damping factor: '))
x = np.zeros((n,n))
print("Original array:")
print(x)
for i in range(n):
    print('page ',i,' has a outgoing edge with: ')
    w=input('any outgoing edge(y/n) :')
    if(w=='n'):
        x[:,i]=0
    c=1
    while(w=='y' and c<n):
        q=int(input('enter the page no :'))
        x[q,i]=1
        if((c+1)<n):
            w=input('any other outgoing edge(y/n) :')
        c=c+1
    if(sum(x[:,i]>0)):
        x[:,i]=x[:,i]/sum(x[:,i])
    print('*'*10)
    #print('-'*20)
print(x) 

enter the number of pages: 3
enter the damping factor: 0.85
Original array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
page  0  has a outgoing edge with: 
any outgoing edge(y/n) :y
enter the page no :1
any other outgoing edge(y/n) :y
enter the page no :2
**********
page  1  has a outgoing edge with: 
any outgoing edge(y/n) :y
enter the page no :2
any other outgoing edge(y/n) :n
**********
page  2  has a outgoing edge with: 
any outgoing edge(y/n) :y
enter the page no :0
any other outgoing edge(y/n) :n
**********
[[0.  0.  1. ]
 [0.5 0.  0. ]
 [0.5 1.  0. ]]


![WhatsApp Image 2019-10-13 at 8 48 06 PM](https://user-images.githubusercontent.com/54896849/66717945-d9e8d600-edfb-11e9-9fbe-1df013ceef11.jpeg)

In [85]:
m=(x.dot(np.ones(n)*d))
c=0
a=[]
for i in range(200):
    m=x.dot(m)
    a.append(m)

for i in range(1,len(a)):
    if([round(elem,5) for elem in list(a[i])]==[round(elem,5) for elem in list(a[i-1])]):
        print(a[i])
        k=a[i]
        break       

[1.02000389 0.5099987  1.01999741]


In [86]:
dic={}
for i in range(n):
    dic[i]=k[i]
print(dic)

{0: 1.0200038909912104, 1: 0.5099987030029294, 2: 1.0199974060058588}


In [87]:
s=sorted(dic.items(), key=lambda x: x[1])
s

[(1, 0.5099987030029294), (2, 1.0199974060058588), (0, 1.0200038909912104)]

In [88]:
# 1-Lowest rank
# n-Highest rank
for i in range(n):
    print("page ",s[i][0]," has PageRank ",i+1)

page  1  has PageRank  1
page  2  has PageRank  2
page  0  has PageRank  3
