In [1]:
import numpy as np
n=int(input('enter the number of pages: '))
d=float(input('enter the damping factor: '))
x = np.zeros((n,n))
print("Original array:")
print(x)
for i in range(n):
    print('page ',i,' has a outgoing edge with: ')
    w=input('any outgoing edge(y/n) :')
    if(w=='n'):
        x[:,i]=0
    c=1
    while(w=='y' and c<n):
        q=int(input('enter the page no :'))
        x[q,i]=1
        if((c+1)<n):
            w=input('any other outgoing edge(y/n) :')
        c=c+1
    if(sum(x[:,i]>0)):
        x[:,i]=x[:,i]/sum(x[:,i])
    print('*'*10)
      #print('-'*20)
print(x)

enter the number of pages: 3
enter the damping factor: 0.85
Original array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
page  0  has a outgoing edge with: 
any outgoing edge(y/n) :y
enter the page no :1
any other outgoing edge(y/n) :y
enter the page no :2
**********
page  1  has a outgoing edge with: 
any outgoing edge(y/n) :y
enter the page no :2
any other outgoing edge(y/n) :n
**********
page  2  has a outgoing edge with: 
any outgoing edge(y/n) :y
enter the page no :0
any other outgoing edge(y/n) :n
**********
[[0.  0.  1. ]
 [0.5 0.  0. ]
 [0.5 1.  0. ]]


![WhatsApp Image 2019-10-13 at 8 48 36 PM](https://user-images.githubusercontent.com/54896849/66717976-45cb3e80-edfc-11e9-9072-5ac0a1182777.jpeg)

In [6]:
y=(np.linalg.inv(np.eye(n)- d*x))
#print(y.shape)

k=((1-d)*np.ones(n))
#print(k.shape)
final=(y.dot(k))
print(list(final))

[1.1633691351045785, 0.6444318824194459, 1.1921989824759749]


In [7]:
dic={}
for i in range(n):
    dic[i]=final[i]
print(dic)

{0: 1.1633691351045785, 1: 0.6444318824194459, 2: 1.1921989824759749}


In [8]:
s=sorted(dic.items(), key=lambda x: x[1])
s

[(1, 0.6444318824194459), (0, 1.1633691351045785), (2, 1.1921989824759749)]

In [9]:
# 1-Lowest rank
# n-Highest rank
for i in range(n):
    print("page ",s[i][0]," has PageRank ",i+1)

page  1  has PageRank  1
page  0  has PageRank  2
page  2  has PageRank  3
